### General settings.
nnsvs_root: "../nnsvs"

## The name of singer
spk: unnamed

## exp tag(for managing experiments)
tag: enunu_training_kit

## Directory of Unzipped singing voice database
# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
db_root: "../singing_database"

## Output directory
# All the generated labels, intermediate files, and segmented wav files
# will be saved in the following directory
out_dir: "data"

## Songs to be excluded from trainig.
exclude_songs: []

### Pyinsy related settings.
## Sinsy dictionary directory
# This singing voice database contains the unvoiced vowels "I" and "U".
# To enable the unvoiced vowels, modified version of sinsy dictionary files
# are needed.
table_path: "dic/kana2phonemes_utf8_for_oto2lab.table"
## HTS-style question used for extracting musical/linguistic context from musicxml files
question_path: "hed/jp_qst_crazy_mono_010_enunu_209D.hed"

# Time-lag constraints to filter outliers
timelag_allowed_range: [-20, 19]
timelag_allowed_range_rest: [-40, 39]
# Audio sampling rate
# CAUTION: Changing sample_rate may affect the dimension number of acoustic features.
# DO NOT CHANGE this unless you know the relationship between the dim of bap and sample_rate.
sample_rate: 44100

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

timelag_features: defaults
duration_features: defaults
acoustic_features: static_deltadelta

###########################################################
#                TRAINING SETTING                         #
###########################################################

# Models
# To customize, put your config or change ones in
# conf/train/{timelag,duration,acoustic}/ and
# specify the config name below
# NOTE: *_model: model definition, *_train: general train configs,
# *_data: data configs (e.g., batch size)

timelag_model: timelag_ffn
timelag_train: myconfig
timelag_data: myconfig

duration_model: duration_lstm
duration_train: myconfig
duration_data: myconfig

acoustic_model: acoustic_conv
acoustic_train: myconfig
acoustic_data: myconfig

# Pretrained model dir (leave empty to disable)
pretrained_expdir:

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
timelag_synthesis: defaults
duration_synthesis: defaults
acoustic_synthesis: defaults

# latest.pth or best.pth
timelag_eval_checkpoint: best_loss.pth
duration_eval_checkpoint: best_loss.pth
acoustic_eval_checkpoint: latest.pth
