python 0_0_0_copy_files.py config.yaml
python 0_0_1_check_lab.py config.yaml
python 0_0_2_force_ust_end_with_rest.py config.yaml
python 0_1_1_ust2lab.py config.yaml
python 0_1_2_merge_rest_full_score.py config.yaml
python 0_1_2_merge_rest_mono_align.py config.yaml
python 0_1_3_round_lab.py config.yaml
python 0_1_4_full2mono.py config.yaml
python 0_2_compare_mono_align_and_mono_score.py config.yaml
python 0_3a_copy_mono_time_to_full.py config.yaml
python 0_3b_segment_lab.py config.yaml
python 0_4_finalize_lab.py config.yaml
python 0_5_generate_train_list.py config.yaml
