# @package _group_

stream_sizes:          [1]
has_dynamic_features:  [false]
stream_weights:        [1]

netG:
  _target_:            nnsvs.model.RMDN
  in_dim:              206
  out_dim:             1
  hidden_dim:          256
  num_layers:          2
  bidirectional:       true
  dropout:             0.5
  num_gaussians:       4
